filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
  ignore_older: 0
  start_position: beginning
  scan_frequency: 1s

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "nginx-filebeat-logs"
